"""add file_size_bytes to documents

Revision ID: 09e57d89a510
Revises: d0cdae644f42
Create Date: 2026-06-20 10:23:03.401279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e57d89a510'
down_revision: Union[str, Sequence[str], None] = 'd0cdae644f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size_bytes', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_size_bytes')
    # ### end Alembic commands ###
