"""
Chat routes.

Endpoints:
  POST   /api/chats                    -> create a new chat scoped to document(s)
  GET    /api/chats                    -> list current user's chats
  GET    /api/chats/{id}               -> get chat metadata + full message history
  DELETE /api/chats/{id}                -> delete a chat (and its messages, cascade)
  POST   /api/chats/{id}/messages       -> send a message, stream back the answer

Streaming + database session note:
  FastAPI's StreamingResponse only starts running the generator AFTER the
  route function returns and the response object is handed to the ASGI
  server. By that point, a `db: Session = Depends(get_db)` session would
  already be closed (get_db's `finally` runs as soon as the route function
  itself returns, not when the generator finishes). So the streaming route
  below opens its OWN session that stays alive for the generator's full
  lifetime, and closes it only once streaming is complete — same pattern
  used for the background task in document_routes.py.
"""

import uuid

from fastapi import APIRouter, Depends, status
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from app.database.connection import get_db, SessionLocal
from app.auth.dependencies import get_current_user
from app.models.user import User
from app.schemas.chat_schema import ChatCreate, ChatResponse, ChatListResponse
from app.schemas.message_schema import MessageCreate, ChatHistoryResponse, MessageResponse
from app.services.chat_service import (
    create_chat,
    list_chats,
    get_chat,
    delete_chat,
    send_message_and_stream,
)
from app.utils.logger import logger

router = APIRouter(prefix="/api/chats", tags=["Chat"])


def _chat_to_response(chat) -> ChatResponse:
    return ChatResponse(
        id=chat.id,
        title=chat.title,
        created_at=chat.created_at,
        document_ids=[d.id for d in chat.documents],
    )


@router.post("", response_model=ChatResponse, status_code=status.HTTP_201_CREATED)
def create(
    payload: ChatCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    chat = create_chat(db, current_user, payload)
    return _chat_to_response(chat)


@router.get("", response_model=ChatListResponse)
def list_all(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    chats = list_chats(db, current_user)
    return ChatListResponse(chats=[_chat_to_response(c) for c in chats], total=len(chats))


@router.get("/{chat_id}", response_model=ChatHistoryResponse)
def get_one(
    chat_id: uuid.UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    chat = get_chat(db, current_user, chat_id)
    return ChatHistoryResponse(
        chat_id=chat.id,
        title=chat.title,
        messages=[MessageResponse.model_validate(m) for m in chat.messages],
    )


@router.delete("/{chat_id}", status_code=status.HTTP_200_OK)
def delete_one(
    chat_id: uuid.UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    delete_chat(db, current_user, chat_id)
    return {"message": "Chat deleted successfully."}


@router.post("/{chat_id}/messages")
def send_message(
    chat_id: uuid.UUID,
    payload: MessageCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Streams the assistant's answer back as plain text chunks, as they're
    generated by Gemini. The frontend (Phase 9) reads this with
    `fetch()` + `ReadableStream` and appends each chunk to the UI live,
    producing the ChatGPT-style "typing" effect.

    IMPORTANT: we verify the chat exists and belongs to current_user HERE,
    using the request-scoped `db` session, BEFORE returning the
    StreamingResponse. This matters because once StreamingResponse starts
    sending bytes, the HTTP status code is already locked in at 200 — any
    error raised *inside* the generator can no longer change that status
    code. Checking ownership upfront means a request for someone else's
    chat correctly gets a 404, rather than a misleading 200 with an error
    message embedded in the streamed body.
    """
    get_chat(db, current_user, chat_id)  # raises 404 here if not found/not owned

    def stream_with_own_session():
        stream_db = SessionLocal()
        try:
            yield from send_message_and_stream(stream_db, current_user, chat_id, payload.content)
        except Exception as e:
            logger.error("Streaming failed for chat %s: %s", chat_id, str(e))
            yield "\n\n[An error occurred while generating the response. Please try again.]"
        finally:
            stream_db.close()

    return StreamingResponse(stream_with_own_session(), media_type="text/plain")
